#Project information
site_name: Bloody-test-subject
site_url: https://takashiwahrkeit.github.io/bloody-test-repo/
site_author: Yevhen Maslov

#Repo info
repo_name: bloody-test-repo
repo_url: https://github.com/takashiwahrkeit/bloody-test-repo

nav:
- Intro: index.md
